### ISSUE TITLE
Dynamic update to server.xml causes exception

### ISSUE THREAD

**Issue by dselvara1** [OpenLiberty/liberty-tools-vscode#174]
Extension version - 0.1.11
Dynamically updating the server.xml causes the following failure in VSCode running on **windows**.

```
C:\guide-liberty-deep-dive\start\inventory> c:\guide-liberty-deep-dive\start\inventory\mvnw.cmd io.openliberty.tools:liberty-maven-plugin:dev -f "c:\guide-liberty-deep-dive\start\inventory\pom.xml"
[INFO] Scanning for projects...
----------- skipping lines to avoid clutter -----------
[INFO] [AUDIT   ] CWWKT0016I: Web application available (default_host): http://localhost:9080/inventory/
[INFO] [AUDIT   ] CWWKZ0003I: The application inventory updated in 3.715 seconds.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:43 min
[INFO] Finished at: 2022-11-09T17:06:20+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.openliberty.tools:liberty-maven-plugin:3.5.1:dev (default-cli) on project inventory: C:\guide-liberty-deep-dive\start\inventory\target\liberty\wlp\usr\servers\defaultServer\messaging\messageStore\Log -> C:\Users\DEVIPR~1\AppData\Local\Temp\tempConfig4554475399748035414\messaging\messageStore\Log: The process cannot access the file because another process has locked a portion of the file.
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Exception in thread "Thread-2" java.lang.NoClassDefFoundError: org/apache/commons/io/file/PathUtils        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1423)
        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:338)
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1206)
        at io.openliberty.tools.common.plugins.util.DevUtil.cleanUpTempConfig(DevUtil.java:1952)   
        at io.openliberty.tools.common.plugins.util.DevUtil.runShutdownHook(DevUtil.java:2003)     
        at io.openliberty.tools.common.plugins.util.DevUtil.access$500(DevUtil.java:97)
        at io.openliberty.tools.common.plugins.util.DevUtil$6.run(DevUtil.java:1990)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.file.PathUtils
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
        ... 7 more
C:\guide-liberty-deep-dive\start\inventory>
```
Server still seems to be running at the background post this exception, so had to stop server and then start again. Just tried to start the first time, got error saying that the server is still running.

**Comment by kathrynkodama** [comment]
@dselvara1 thanks for reporting, what change did you make to the server.xml that resulted in the above exception? Are you able to recreate the issue and provide the debug output (`mvn liberty:dev -X`)?

**Comment by TrevCraw** [comment]
@dselvara1 before attempting to recreate the issue, could you please update the Liberty Maven Plugin in the POM file to the latest version - `3.7.1`

**Comment by dselvara1** [comment]
With Liberty Maven Plugin 3.7.1 I dont see the issue any more.  The openliberty deepdive guide pom.xml could be updated to have the right version of the plugin.
