### ISSUE TITLE
UnsupportedOperationException in the output tabs for language servers.

### ISSUE THREAD

**Issue by turkeylurkey** [OpenLiberty/liberty-tools-vscode#207]
lsp4jakarta and lcls output tabs included this exception
Dec. 12, 2022 3:58:14 P.M. org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleNotification
WARNING: Notification threw an exception: {
  "jsonrpc": "2.0",
  "method": "$/setTrace",
  "params": {
    "value": "off"
  }
}
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at io.openliberty.tools.langserver.common.ParentProcessWatcher.lambda$apply$0(ParentProcessWatcher.java:154)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 12 more
Caused by: java.lang.UnsupportedOperationException
	at org.eclipse.lsp4j.services.LanguageServer.setTrace(LanguageServer.java:125)
	... 17 more

**Comment by TrevCraw** [comment]
Hit this issue again while trying to recreate #247

**Comment by yeekangc** [comment]
Unsure how we can recreate this issue.

**Comment by TrevCraw** [comment]
@gilbysunil14 ran into this issue again and opened a duplicate here: https://github.com/OpenLiberty/liberty-tools-vscode/issues/346

**Comment by gilbysunil14** [comment]
Found similar issue in eclipse-jdtls repo (https://github.com/eclipse-jdtls/eclipse.jdt.ls/issues/2891) where an `UnsupportedOperationException` is thrown at `org.eclipse.lsp4j.services.LanguageServer.setTrace`. A proposed solution can be found at https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/2893 to make the '$/setTrace' as empty to avoid throwing UnsupportedOperationException.

A similar change for `setTrace()` as was done in eclipse-lsp4j repo for `getNotebookDocumentService()` here: https://github.com/eclipse-lsp4j/lsp4j/commit/04b0c6112f0a94140e22b8b15bb5a90d5a0ed851#diff-c253172d13cae9e4a8c919ba451df40be7096aad30d01638383c6ed0497e7f19R92

**Comment by gilbysunil14** [comment]
Closing this issue since the solution has been provided in the lsp4jakarta PR https://github.com/eclipse/lsp4jakarta/pull/531
