### ISSUE TITLE
Vscode test run failing on Windows platform

### ISSUE THREAD

**Issue by dselvara2** [OpenLiberty/liberty-tools-vscode#265]
Windows platform tests were working as expected until this run - https://github.com/OpenLiberty/liberty-tools-vscode/actions/runs/5079475331 
18 tests were passing and 3 failing including docker and attach debugger tests.
Post this multiple changes have happened to fix other issues in the tests and currently windows plaform has been removed from the test run. 
Before removal of the windows platform, if we check the last run - https://github.com/OpenLiberty/liberty-tools-vscode/actions/runs/5186451875/jobs/9347567786 - we can see the below exception -

_Failed Installing Extensions: file:///d%3A/a/liberty-tools-vscode/liberty-tools-vscode/liberty-dev-vscode-ext-23.0.6-SNAPSHOT.vsix
Error: Command failed: set ELECTRON_RUN_AS_NODE=1 && "D:\a\liberty-tools-vscode\liberty-tools-vscode\test-resources\VSCode-win32-x64-archive\Code.exe" "D:\a\liberty-tools-vscode\liberty-tools-vscode\test-resources\VSCode-win32-x64-archive\resources\app\out\cli.js" --ms-enable-electron-run-as-node --force --install-extension "D:\a\liberty-tools-vscode\liberty-tools-vscode\liberty-dev-vscode-ext-23.0.6-SNAPSHOT.vsix"_

**Comment by vkavitha** [comment]
As discussed "Failed Installing Extensions: file:///d%3A/a/liberty-tools-vscode/liberty-tools-vscode/liberty-dev-vscode-ext-23.0.6-SNAPSHOT.vsix" is related to the change introduced in the tools to restrict installation only on 1.78 and above. What we should check is on the test run in supported platform <ie 1.78 and 1.79> . Pls check it once the https://github.com/OpenLiberty/liberty-tools-vscode/pull/262 is merged in to main which has the basic test-automation integration

**Comment by dselvara2** [comment]
created a new branch "windows-test" post the #262 merge
Enabled windows tests. Windows run is still failing with same error posted above

```
Failed Installing Extensions: file:///d%3A/a/liberty-tools-vscode/liberty-tools-vscode/liberty-dev-vscode-ext-23.0.6-SNAPSHOT.vsix
Error: Command failed: set ELECTRON_RUN_AS_NODE=1 && "D:\a\liberty-tools-vscode\liberty-tools-vscode\test-resources\VSCode-win32-x64-archive\Code.exe" "D:\a\liberty-tools-vscode\liberty-tools-vscode\test-resources\VSCode-win32-x64-archive\resources\app\out\cli.js" --ms-enable-electron-run-as-node --force --install-extension "D:\a\liberty-tools-vscode\liberty-tools-vscode\liberty-dev-vscode-ext-23.0.6-SNAPSHOT.vsix"
    at checkExecSyncError (node:child_process:885:11)
    at Object.execSync (node:child_process:957:15)
    at CodeUtil.installExt (D:\a\liberty-tools-vscode\liberty-tools-vscode\node_modules\vscode-extension-tester\out\util\codeUtil.js:139:23)
    at CodeUtil.installExtension (D:\a\liberty-tools-vscode\liberty-tools-vscode\node_modules\vscode-extension-tester\out\util\codeUtil.js:119:14)
    at ExTester.<anonymous> (D:\a\liberty-tools-vscode\liberty-tools-vscode\node_modules\vscode-extension-tester\out\extester.js:86:30)
    at Generator.next (<anonymous>)
    at fulfilled (D:\a\liberty-tools-vscode\liberty-tools-vscode\node_modules\vscode-extension-tester\out\extester.js:19:58)
+ rc=1
```

Job run - https://github.com/OpenLiberty/liberty-tools-vscode/actions/runs/5275220359/jobs/9540458380

**Comment by dselvara2** [comment]
Hard coded vscode version to 1.78.2 just to see if the windows test goes through because the error message clearly says the extension is not compatible with 1.77.0
`Error: Unable to install extension 'open-liberty.liberty-dev-vscode-ext' as it is not compatible with VS Code '1.77.0'.`

The tests are running with 1.78.2. Gradle tests went thru. But maven tests other than the "Start" tests are failing with below error.
Warning:  Unrecognized command: mvn io.openliberty.tools:liberty-maven-plugin:dev -DhotTests=true -f "d:\a\liberty-tools-vscode\liberty-tools-vscode\src\test\resources\maven\liberty.maven.test.wrapper.app\pom.xml". To see the help menu, type 'h' and press Enter.  

As the "Start" test is passing, mvn should be available, so in between tests why mvn becomes unrecognized needs to be investigated.
W.r.to windows platform, the test for devmode action is to simulate the click on the action "Start" or "Start..." or "Run Test". Its upto the extension to open the terminal and run the mvn command for the correspoding dev mode action.

**Comment by dselvara2** [comment]
Hello @TrevCraw, I have created a branch (`windows-test`) to test why the windows run  is failing. And updated my observations above. This issue has to be tried on few vscode versions to observe the behavior. This could be an environmental setup issue where the mvn install is not available. Can you pls assign the task to the new team taking over. Thanks.

**Comment by aparnamichael** [comment]
The tests are working fine in windows local machine. In GHA, I am getting the following error :

Error: Command failed: cd vscodeCdTmrs && tar -xvf C:\Users\RUNNER~1\AppData\Local\Temp\test-resources\stable.zip
tar: Cannot connect to C: resolve failed
    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:303:5)
