### ISSUE TITLE
Regression 23.0.12:  while testing 'Start in container' using podman, generating an empty .libertyls folder in Mac OS.

### ISSUE THREAD

**Issue by aparnamichael** [OpenLiberty/liberty-tools-vscode#315]
OS: Mac
VS code: 1.84.2
Start in container using docker: everything working as expected.

While testing start in container using podman empty .libertyls folder is generating and server.xml is taking default cached 23.0.0.9.xsd file.

In server.xml, I am getting feature, loggging, keystore etc.. but list of features completion/hover info is not getting and diagnostics is not working after running start in container using podman. Tested with both gradle and maven project, in both I am seeing this same issue.

![image](https://github.com/OpenLiberty/liberty-tools-vscode/assets/114654953/05fe803d-fbbd-4dba-88c9-be4474e78744)

<img width="1422" alt="image" src="https://github.com/OpenLiberty/liberty-tools-vscode/assets/114654953/224057f8-8854-4eb0-ae9d-4b03275288e2">

![image](https://github.com/OpenLiberty/liberty-tools-vscode/assets/114654953/de1a7e1e-13ab-4469-992d-2955b8d72748)

**Comment by aparnamichael** [comment]
Logs:
`[Info  - 20:58:21] Nov 20, 2023 08:58:21 org.eclipse.lemminx.XMLLanguageServer initialize()
Message: Initializing XML Language server
LemMinX Server info:
 - Version : 0.26.1
 - Java : /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home
 - VM Version : 17.0.7
 - Git 8379294 - [maven-release-plugin] prepare release 0.26.1
[Info  - 20:58:22] Nov 20, 2023 08:58:21 io.openliberty.tools.langserver.lemminx.services.LibertyProjectsManager setWorkspaceFolders()
Message: Checking Liberty workspace for sub-modules: file:/Users/aparnacmichael/Documents/app-name-vscodeone
[Info  - 20:58:22] Nov 20, 2023 08:58:21 io.openliberty.tools.langserver.lemminx.services.LibertyProjectsManager setWorkspaceFolders()
Message: Skipping parent module: file:/Users/aparnacmichael/Documents/app-name-vscodeone/
[Info  - 20:58:22] Nov 20, 2023 08:58:21 io.openliberty.tools.langserver.lemminx.services.LibertyProjectsManager setWorkspaceFolders()
Message: Adding Liberty workspace by default: file:/Users/aparnacmichael/Documents/app-name-vscodeone
[Info  - 20:58:22] Nov 20, 2023 08:58:21 io.openliberty.tools.langserver.lemminx.LibertyExtension doSave()
Message: Liberty XML settings updated
[Info  - 20:58:22] Nov 20, 2023 08:58:22 io.openliberty.tools.langserver.lemminx.util.LibertyUtils getLibertyPropertiesFile()
Message: Could not find openliberty.properties file in Liberty installation: /Users/aparnacmichael/Documents/app-name-vscodeone/target/liberty/wlp
[Info  - 20:58:22] Nov 20, 2023 08:58:22 io.openliberty.tools.langserver.lemminx.LibertyXSDURIResolver resolve()
Message: Using cached Liberty schema file located at: /Users/aparnacmichael/.lemminx/cache/https/github.com/OpenLiberty/liberty-language-server/blob/master/lemminx-liberty/src/main/resources/schema/xsd/liberty/server-cached-23.0.0.9.xsd
[Info  - 20:58:22] Nov 20, 2023 08:58:22 io.openliberty.tools.langserver.lemminx.services.LibertyWorkspace getFeatureListGraph()
Message: Retrieving default cached feature list for workspace file:/Users/aparnacmichael/Documents/app-name-vscodeone
[Info  - 20:58:22] Nov 20, 2023 08:58:22 io.openliberty.tools.langserver.lemminx.services.FeatureService getDefaultFeatureList()
Message: Using cached Liberty featurelist xml file located at: /Users/aparnacmichael/.lemminx/cache/https/github.com/OpenLiberty/liberty-language-server/blob/master/lemminx-liberty/src/main/resources/featurelist-cached-23.0.0.9.xml
[Info  - 20:58:22] Nov 20, 2023 08:58:22 io.openliberty.tools.langserver.lemminx.services.LibertyWorkspace getFeatureListGraph()
Message: Config element validation for missing features enabled for workspace: file:/Users/aparnacmichael/Documents/app-name-vscodeone
[Info  - 20:58:22] Nov 20, 2023 08:58:22 io.openliberty.tools.langserver.lemminx.util.LibertyUtils getLibertyPropertiesFile()
Message: Could not find openliberty.properties file in Liberty installation: /Users/aparnacmichael/Documents/app-name-vscodeone/target/liberty/wlp
[Info  - 20:58:22] Nov 20, 2023 08:58:22 io.openliberty.tools.langserver.lemminx.services.FeatureService getDefaultFeatures()
Message: Returning default list of features
[Info  - 20:58:22] Nov 20, 2023 08:58:22 io.openliberty.tools.langserver.lemminx.services.FeatureService getDefaultFeatures()
Message: Returning default list of features
[Info  - 20:58:22] Nov 20, 2023 08:58:22 io.openliberty.tools.langserver.lemminx.services.FeatureService getDefaultFeatures()
Message: Returning default list of features
[Info  - 20:58:22] Nov 20, 2023 08:58:22 io.openliberty.tools.langserver.lemminx.util.LibertyUtils getLibertyPropertiesFile()
Message: Could not find openliberty.properties file in Liberty installation: /Users/aparnacmichael/Documents/app-name-vscodeone/target/liberty/wlp
[Info  - 20:58:22] Nov 20, 2023 08:58:22 io.openliberty.tools.langserver.lemminx.LibertyXSDURIResolver resolve()
Message: Using cached Liberty schema file located at: /Users/aparnacmichael/.lemminx/cache/https/github.com/OpenLiberty/liberty-language-server/blob/master/lemminx-liberty/src/main/resources/schema/xsd/liberty/server-cached-23.0.0.9.xsd
[Info  - 20:58:22] Nov 20, 2023 08:58:22 io.openliberty.tools.langserver.lemminx.util.LibertyUtils getLibertyPropertiesFile()
Message: Could not find openliberty.properties file in Liberty installation: /Users/aparnacmichael/Documents/app-name-vscodeone/target/liberty/wlp
[Info  - 20:58:22] Nov 20, 2023 08:58:22 io.openliberty.tools.langserver.lemminx.LibertyXSDURIResolver resolve()
Message: Using cached Liberty schema file located at: /Users/aparnacmichael/.lemminx/cache/https/github.com/OpenLiberty/liberty-language-server/blob/master/lemminx-liberty/src/main/resources/schema/xsd/liberty/server-cached-23.0.0.9.xsd
[Warn  - 20:58:22] Nov 20, 2023 08:58:22 org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation()
Message: Unmatched cancel notification for request id 2
[Error - 20:59:27] Nov 20, 2023 08:59:27 io.openliberty.tools.langserver.lemminx.LibertyXSDURIResolver resolve()
Message: Error: Unable to generate the Liberty schema from the target Liberty runtime: Cannot run program "docker": error=2, No such file or directory
[Info  - 20:59:27] Nov 20, 2023 08:59:27 io.openliberty.tools.langserver.lemminx.LibertyXSDURIResolver resolve()
Message: Using cached Liberty schema file located at: /Users/aparnacmichael/.lemminx/cache/https/github.com/OpenLiberty/liberty-language-server/blob/master/lemminx-liberty/src/main/resources/schema/xsd/liberty/server-cached-23.0.0.9.xsd
[Info  - 20:59:27] Nov 20, 2023 08:59:27 io.openliberty.tools.langserver.lemminx.services.LibertyWorkspace getFeatureListGraph()
Message: Generating installed features list and storing to cache for workspace file:/Users/aparnacmichael/Documents/app-name-vscodeone
[Info  - 20:59:27] Nov 20, 2023 08:59:27 io.openliberty.tools.langserver.lemminx.services.ContainerService generateFeatureListFromContainer()
Message: Generating feature list file for container at: /Users/aparnacmichael/Documents/app-name-vscodeone/target/.libertyls/featurelist.xml
[Error - 20:59:27] Nov 20, 2023 08:59:27 io.openliberty.tools.langserver.lemminx.LibertyXSDURIResolver resolve()
Message: Error: Unable to generate the Liberty schema from the target Liberty runtime: Cannot run program "docker": error=2, No such file or directory
[Info  - 20:59:27] Nov 20, 2023 08:59:27 io.openliberty.tools.langserver.lemminx.LibertyXSDURIResolver resolve()
Message: Using cached Liberty schema file located at: /Users/aparnacmichael/.lemminx/cache/https/github.com/OpenLiberty/liberty-language-server/blob/master/lemminx-liberty/src/main/resources/schema/xsd/liberty/server-cached-23.0.0.9.xsd
[Error - 20:59:27] Nov 20, 2023 08:59:27 org.eclipse.lemminx.services.XMLDiagnostics doExtensionsDiagnostics()
Message: Error while processing diagnostics for the participant 'io.openliberty.tools.langserver.lemminx.LibertyDiagnosticParticipant'.
java.lang.RuntimeException: Cannot run program "docker": error=2, No such file or directory
    at io.openliberty.tools.langserver.lemminx.services.ContainerService.execContainerCmd(ContainerService.java:212)
    at io.openliberty.tools.langserver.lemminx.services.ContainerService.execContainerCmd(ContainerService.java:181)
    at io.openliberty.tools.langserver.lemminx.services.ContainerService.containerExec(ContainerService.java:69)
    at io.openliberty.tools.langserver.lemminx.services.ContainerService.generateFeatureListFromContainer(ContainerService.java:163)
    at io.openliberty.tools.langserver.lemminx.services.FeatureService.getInstalledFeaturesList(FeatureService.java:345)
    at io.openliberty.tools.langserver.lemminx.services.LibertyWorkspace.getFeatureListGraph(LibertyWorkspace.java:260)
    at io.openliberty.tools.langserver.lemminx.LibertyDiagnosticParticipant.validateDom(LibertyDiagnosticParticipant.java:85)
    at io.openliberty.tools.langserver.lemminx.LibertyDiagnosticParticipant.doDiagnostics(LibertyDiagnosticParticipant.java:69)
    at org.eclipse.lemminx.services.XMLDiagnostics.doExtensionsDiagnostics(XMLDiagnostics.java:67)
    at org.eclipse.lemminx.services.XMLDiagnostics.doDiagnostics(XMLDiagnostics.java:49)
    at org.eclipse.lemminx.services.XMLLanguageService.doDiagnostics(XMLLanguageService.java:190)
    at org.eclipse.lemminx.services.XMLLanguageService.publishDiagnostics(XMLLanguageService.java:204)
    at org.eclipse.lemminx.XMLTextDocumentService.validate(XMLTextDocumentService.java:716)
    at org.eclipse.lemminx.XMLTextDocumentService.lambda$validate$35(XMLTextDocumentService.java:691)
    at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
    at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

[Error - 20:59:27] Nov 20, 2023 08:59:27 io.openliberty.tools.langserver.lemminx.LibertyXSDURIResolver resolve()
Message: Error: Unable to generate the Liberty schema from the target Liberty runtime: Cannot run program "docker": error=2, No such file or directory
[Info  - 20:59:27] Nov 20, 2023 08:59:27 io.openliberty.tools.langserver.lemminx.LibertyXSDURIResolver resolve()
Message: Using cached Liberty schema file located at: /Users/aparnacmichael/.lemminx/cache/https/github.com/OpenLiberty/liberty-language-server/blob/master/lemminx-liberty/src/main/resources/schema/xsd/liberty/server-cached-23.0.0.9.xsd

`
