### ISSUE TITLE
VS Code integration tests is failing.

### ISSUE THREAD

**Issue by aparnamichael** [OpenLiberty/liberty-tools-vscode#324]
Now the tests are failing by throwing the following error:

HTTPError: Response code 404 (Not Found)
    at Request._onResponseBase (/Users/runner/work/liberty-tools-vscode/liberty-tools-vscode/node_modules/got/dist/source/core/index.js:913:31)
    at Request._onResponse (/Users/runner/work/liberty-tools-vscode/liberty-tools-vscode/node_modules/got/dist/source/core/index.js:948:24)
    at ClientRequest.<anonymous> (/Users/runner/work/liberty-tools-vscode/liberty-tools-vscode/node_modules/got/dist/source/core/index.js:962:23)
    at Object.onceWrapper (node:events:633:26)
    at ClientRequest.emit (node:events:530:35)

**Comment by aparnamichael** [comment]
From the logs, we understood that it is failing while running "npm run test". "test" is defined as "test": "npm run test-compile && extest setup-and-run -o .vscode/settings.json 'out/test/*.js'".  'npm run test-compile' is working. As a next step, we have updated the extest framework with the latest, after that 404 error gone. 
Now error is coming for 'clipboardy' node module. 
Error [ERR_REQUIRE_ESM]: require() of ES Module node_modules/clipboardy/index.js from out/test/utils/testUtils.js not supported.
Instead change the require of index.js in out/test/utils/testUtils.js to a dynamic import() which is available in all CommonJS modules.
